config/routes.rb
# Routes are the entry point to everything 
# that can happen in your application
# for resources, use only routes you will use
# so that when a dev runs 'rake routes'
# they only see what is being used, what can really be done.
# PRUNE YOUR ROUTES

# User will type url into a browser
# sends requests to your server
# ActionDispatch will take url
# and determine what to do
# (typically end up in a controller at an action)

Shouter::Application.routes.draw do
  root to: 'homes#show', via: :get
  # use 'resource singular' for singleton resource
  # (meaning only one instance that is available globally)
  # singleton resource does not have an id
  # url will be: /dashboard (singular)
  # controller will be dashboards_controller (plural)
  resource :dashboard, only: [:show]
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :shouts, only: [:show]
  resources :text_shouts, only: [:create]
  resources :photo_shouts, only: [:create]
end

app/models/photo_shout.rb
class PhotoShout < ActiveRecord::Base
# has_attached_file :image
  has_attached_file :image, styles: {
    shout: "200X200>"
  }
end

app/models/shout.rb
class Shout < ActiveRecord::Base
  belongs_to :user
#  We are using Strong Parameters so we do not
#  need the auto generated attr_accessible method:
#  attr_accessible :body

  # pass default scope a block, in rails 4 it will be required
# default_scope { order("created_at DESC") }

# BUT default scopes are evil
# so you can use a normal scope
# Note that the -> operator is a 'lambda literal'
  scope :ordered, -> { order('created_at DESC') }

# scopes are a subset of a collection
# Could also use a class method:
# def self.ordered
#   order("created_at DESC") 
# end

# OR you could add '.order('created_at DESC')'
# to @shouts = current_user.shouts
# in Dashboards Controller, and it would work
  belongs_to :content, polymorphic: true

  validates_associated :content
end

app/models/text_shout.rb
class TextShout < ActiveRecord::Base
  attr_accessible :body
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :shouts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers
  protect_from_forgery
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @text_shout = TextShout.new
    @photo_shout = PhotoShout.new
    @shouts = current_user.shouts.ordered
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_filter :check_logged_in_user
  def show
  end

  # private methods - because controllers can tell other objects
  # what its actions are and we don't want to show private methods
  private

  def check_logged_in_user
    if signed_in?
      redirect_to dashboard_path
    end
  end
end

app/controllers/photo_shouts_controller.rb
class PhotoShoutsController < ApplicationController
  def create
    content = build_content
    shout = current_user.shouts.build(content: content)
    if shout.save
      redirect_to dashboard_path
    else
      flash.alert = 'Could not shout.'
      redirect_to dashboard_path
    end
  end

  private

  def build_content
    PhotoShout.new(photo_shout_parameters)
  end

  def photo_shout_parameters
    params.require(:photo_shout).permit(:image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  respond_to :html

  def new
  end

  def create
    user = authenticate_session(session_params)
    sign_in(user) or set_flash_message
    respond_with user, location: root_path
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def set_flash_message
    flash.now.notice = "Invalid username or password"
  end

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/shouts_controller.rb
class ShoutsController < ApplicationController
  def show
    @shout = Shout.find(params[:id])
  end

end

app/controllers/text_shouts_controller.rb
class TextShoutsController < ApplicationController
  def create
    content = build_content
    shout = current_user.shouts.build(content: content)
    if shout.save
      redirect_to dashboard_path
    else
      flash.alert = 'Could not shout.'
      redirect_to dashboard_path
    end
  end

  private

  def build_content
    TextShout.new(text_shout_parameters)
  end

  def text_shout_parameters
    params.require(:text_shout).permit(:body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html

  def show
    @user = User.find(params[:id])
    @shouts = @user.shouts
  end

  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)
    sign_in(@user)
    respond_with @user, location: root_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboards/show.html.erb
<%= form_for @text_shout do |form| %>
  <%= form.text_field :body, placeholder: 'Shout content here' %>
  <%= form.submit 'Shout!' %>
<% end %>

<%= form_for @photo_shout do |form| %>
  <%= form.file_field :image %>
  <%= form.submit 'Shout!' %>
<% end %>

<%= render @shouts %>

app/views/homes/show.html.erb
Welcome to Shouter!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shouter</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div>
    <% if signed_in? %>
      <%= link_to current_user.username, dashboard_path %>
      <%= link_to 'Sign out', session_path, method: :delete %>
    <% else %>
      <%= link_to 'Sign in', new_session_path %>
      <%= link_to 'Sign up', new_user_path %>
    <% end %>
  </div>

  <% if alert %>
    <p><%= alert %></p>
  <% end %>
<%= yield %>

</body>
</html>

app/views/photo_shouts/_photo_shout.html.erb
<%= link_to image_tag(photo_shout.image.url(:shout)), photo_shout.image.url %>

app/views/shouts/_shout.html.erb
<%= div_for shout do %>
  <%= link_to shout.user.username, shout.user %>
  shouted
  <%= render shout.content %>
  <%= link_to time_ago_in_words(shout.created_at), shout %>
<% end %>

app/views/shouts/show.html.erb
<%= render @shout %>

app/views/text_shouts/_text_shout.html.erb
<%= text_shout.body %>

app/views/users/new.html.erb
<%= form_for @user do |form| %>
  <div>
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<%= render @shouts %>